## Uncomment when necessary
# use a base image
# FROM

# install any dependencies ... REPLACE xyz
#RUN apk add --update xyz

# copy the bootstrap.sh file to /
#COPY

# make the bootstrap.sh file executable by running chmod +x <file>
#RUN

#specify the CMD should be in list format
#CMD [ "" ]




